name: Tests

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check isort
        uses: isort/isort-action@v1
        with:
          configuration: --profile black --check --df -v --split-on-trailing-comma

      - name: Check ruff
        uses: chartboost/ruff-action@v1
        with:
          args: --no-fix --verbose --config pyproject.toml

      - name: Check black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --config pyproject.toml"

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "py39-cover (ubuntu)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39-cover"
            os: "ubuntu-latest"
          - name: "py39-nocov (ubuntu)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39-nocov"
            os: "ubuntu-latest"
          - name: "py39-nocov (windows)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39-nocov"
            os: "windows-latest"
          - name: "py39-nocov (macos)"
            python: "3.9"
            toxpython: "python3.9"
            python_arch: "x64"
            tox_env: "py39-nocov"
            os: "macos-latest"
          - name: "py310-nocov (ubuntu)"
            python: "3.10"
            toxpython: "python3.10"
            python_arch: "x64"
            tox_env: "py310-nocov"
            os: "ubuntu-latest"
          - name: "py311-nocov (ubuntu)"
            python: "3.11"
            toxpython: "python3.11"
            python_arch: "x64"
            tox_env: "py311-nocov"
            os: "ubuntu-latest"
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.python_arch }}
      - name: Install dependencies
        run: |
          python -mpip install --progress-bar=off -r ci/requirements.txt
          virtualenv --version
          pip --version
          tox --version
          pip list --format=freeze
      - name: Test
        env:
          TOXPYTHON: "${{ matrix.toxpython }}"
        run: >
          tox -e ${{ matrix.tox_env }} -v
